# Use Node.js for development
FROM node:20-alpine

WORKDIR /gibbs-react

# Copy package.json and package-lock.json first
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project
COPY . .

# Expose the necessary port
EXPOSE 4000

# Use nodemon for hot reloading in development
CMD ["npm", "run", "dev"]
