# Use Node.js for development
FROM node:20-alpine

# Set working directory inside the container
WORKDIR /gibbs-react

# Copy package.json and package-lock.json first
COPY package.json /package.json

# Install dependencies (including dev dependencies)
RUN npm install

# Copy the rest of the project files
COPY . .

# Expose the necessary port
EXPOSE 4000

# Use nodemon for hot reloading in development
CMD ["npm", "run", "dev"]
